# Generated by Django 3.1.3 on 2020-11-30 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_post_po'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postname', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('ex_fk', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.question')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
